import { useEffect,useState } from 'react';
import { Activity, Database, Droplets, FlaskConical, Menu, ShieldCheck, FileText, ChevronRight } from 'lucide-react';
import { LineChart, Line, CartesianGrid, XAxis, YAxis, Tooltip, ResponsiveContainer, Legend } from 'recharts';

type Metric={mae:number;rmse:number;bias:number};
type Result={station_id:string;station_name:string;rain_station:string;pair_distance_km:number;horizon_hours:number;train_n:number;test_n:number;train_start:string;train_end:string;test_start:string;test_end:string;metrics:Record<string,Metric>;series:{time:string;actual:number;predicted:number;persistence:number}[];event_checks:{event_id:string;occurred_at:string;distance_km:number;predicted_tma:number;observed_tma:number;issue_time:string}[]};
type Study={status:string;generated_at:string;split:string;counts:{rain_stations:number;tma_stations:number;regional_flood_reports:number;experiments:number};limitations:string[];results:Result[]};
const names:Record<string,string>={rain_only:'Sinyal hujan',rain_and_tma:'Hujan + histori TMA',tma_only:'Histori TMA',persistence:'Persistence'};

export function StudyApp(){
  const [study,setStudy]=useState<Study>();const [error,setError]=useState(''); const [selection,setSelection]=useState(0);const [view,setView]=useState('overview');const [open,setOpen]=useState(false);
  useEffect(()=>{const controller=new AbortController();fetch('/api/v1/study',{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('Hasil kajian belum tersedia. Jalankan ekstraksi dan training.');return r.json();}).then(r=>setStudy(r.data)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[]);
  const result=study?.results[selection];
  const nav=[{key:'overview',title:'Ringkasan kajian',icon:Activity},{key:'model',title:'Prediksi tinggi muka air',icon:FlaskConical},{key:'events',title:'Verifikasi laporan',icon:ShieldCheck},{key:'quality',title:'Data & metodologi',icon:Database}];
  return <div className="study-app">
    <header className="study-header"><button className="mobile-toggle" aria-label="Buka navigasi" onClick={()=>setOpen(!open)}><Menu size={20}/></button><a className="study-brand" href="#"><Droplets/>FloodSense</a><span className="header-sub">Hydrology Research</span><span className="study-tag">Kajian awal</span><span className="avatar">FS</span></header>
    <aside className={open?'study-sidebar expanded':'study-sidebar'}><small>RUANG KERJA</small>{nav.map(n=><button key={n.key} className={view===n.key?'selected':''} onClick={()=>{setView(n.key);setOpen(false);}}><n.icon size={17}/>{n.title}<ChevronRight size={13}/></button>)}<div className="sidebar-note"><FileText size={20}/><strong>Hujan → TMA → laporan banjir</strong><p>Eksperimen historis untuk menilai hubungan waktu dan kemampuan prediksi.</p></div><footer>GovTechAthon 2026</footer></aside>
    <main className="study-main"><div className="breadcrumb">Kajian hidrologi <ChevronRight size={12}/> {nav.find(n=>n.key===view)?.title}</div><div className="page-heading"><div><h1>{nav.find(n=>n.key===view)?.title}</h1><p>Evaluasi prediksi tinggi muka air menggunakan sinyal curah hujan dan histori sensor.</p></div><span className="status">Experiment</span></div>
      {error&&<div role="alert" className="study-alert">{error}</div>}
      {!study&&!error&&<p>Memuat hasil kajian historis…</p>}
      {study&&<><div className="study-stats"><Stat value={study.counts.rain_stations} label="Pos hujan"/><Stat value={study.counts.tma_stations} label="Pos TMA"/><Stat value={study.counts.regional_flood_reports} label="Laporan regional dalam periode"/><Stat value={study.counts.experiments} label="Eksperimen lolos kecukupan"/></div>
      <div className="study-alert"><strong>Eksperimen data historis.</strong> Satuan dan interval pengukuran hujan masih perlu validasi. Pasangan pos memakai jarak terdekat sebagai pendekatan eksploratif.</div>
      {view!=='quality'&&<div className="study-controls"><label htmlFor="experiment">Pasangan pos & horizon</label><select id="experiment" value={selection} onChange={e=>setSelection(Number(e.target.value))}>{study.results.map((r,i)=><option key={i} value={i}>{r.station_name} ← {r.rain_station} · {r.horizon_hours} jam</option>)}</select></div>}
      {!result&&view!=='quality'&&<article className="study-panel">Belum ada pasangan dengan data lengkap yang memenuhi minimum training dan test.</article>}
      {result&&(view==='overview'||view==='model')&&<><article className="study-panel"><div className="panel-title"><div><h2>TMA aktual dan prediksi</h2><p>{result.station_name} · horizon {result.horizon_hours} jam · pasangan hujan berjarak {result.pair_distance_km} km</p></div><span>168 sampel test terakhir</span></div><div className="study-chart"><ResponsiveContainer width="100%" height={320}><LineChart data={result.series}><CartesianGrid stroke="#e3e6ed" vertical={false}/><XAxis dataKey="time" minTickGap={55} tickFormatter={t=>String(t).slice(5,16)} tick={{fontSize:10}}/><YAxis width={55} tick={{fontSize:11}} domain={['auto','auto']}/><Tooltip/><Legend/><Line dataKey="actual" name="TMA aktual" stroke="#31374a" dot={false} strokeWidth={2}/><Line dataKey="predicted" name="Hujan + TMA" stroke="#3874ff" dot={false} strokeWidth={2}/><Line dataKey="persistence" name="Persistence" stroke="#e5780b" dot={false} strokeDasharray="4 4"/></LineChart></ResponsiveContainer></div><p className="caption">Skala mengikuti nilai TINGGI_AIR sumber. Timestamp mempertahankan waktu database sampai zona waktu sumber terkonfirmasi.</p></article>
      <article className="study-panel"><h2>Perbandingan pada periode test yang sama</h2><p>Training: {result.train_start} – {result.train_end}. Test: {result.test_start} – {result.test_end}.</p><div className="table-scroll"><table><thead><tr><th>Model</th><th>MAE ↓</th><th>RMSE ↓</th><th>Bias</th></tr></thead><tbody>{Object.entries(result.metrics).map(([key,m])=><tr key={key}><td>{names[key]}</td><td>{m.mae.toFixed(3)}</td><td>{m.rmse.toFixed(3)}</td><td>{m.bias.toFixed(3)}</td></tr>)}</tbody></table></div><p className="caption">{result.train_n.toLocaleString('id-ID')} sampel training · {result.test_n.toLocaleString('id-ID')} sampel test. Kontribusi hujan dinilai terhadap model histori TMA, serta baseline persistence.</p></article></>}
      {result&&(view==='overview'||view==='events')&&<article className="study-panel"><h2>Pencocokan laporan banjir</h2><p>{result.event_checks.length} laporan terkait dalam radius 5 km dan hingga 6 jam setelah interval prediksi. Ini merupakan pencocokan awal, belum verifikasi hidrologis.</p><div className="table-scroll"><table><thead><tr><th>Waktu kejadian</th><th>Jarak</th><th>TMA prediksi</th><th>TMA aktual</th></tr></thead><tbody>{result.event_checks.map((e,i)=><tr key={i}><td>{e.occurred_at}</td><td>{e.distance_km} km</td><td>{e.predicted_tma.toFixed(2)}</td><td>{e.observed_tma.toFixed(2)}</td></tr>)}</tbody></table>{result.event_checks.length===0&&<p className="empty-study">Tidak ada laporan yang cocok dengan kriteria pada periode test pasangan ini. Ini tidak berarti tidak terjadi banjir.</p>}</div></article>}
      {view==='quality'&&<article className="study-panel"><h2>Metodologi dan keterbatasan</h2><p>Split kronologis: {study.split}. Nilai hilang tidak diisi dengan nol. Konflik snapshot dikeluarkan sebelum agregasi per jam.</p><ol>{study.limitations.map(l=><li key={l}>{l}</li>)}</ol><h3>Kebutuhan validasi berikutnya</h3><p>Konfirmasi satuan dan reset akumulasi hujan, zona waktu sensor, serta keterhubungan DAS/polder. Setelah itu lakukan rolling-origin backtest dan review laporan per kejadian.</p></article>}
      <footer className="study-footer">FloodSense · Kajian historis <span>Hasil: {study.generated_at.replace('T',' ').slice(0,19)}</span></footer></>}
    </main></div>;
}
function Stat({value,label}:{value:number;label:string}){return <div><strong>{value.toLocaleString('id-ID')}</strong><span>{label}</span></div>;}
